### PR TITLE
feat: add bloom/bloom-classic(apps) dci-icons

### PR DESCRIPTION
**Pull request by kegechen**
dci-icon-theme  -m "*.svg" /usr/share/icons/bloom/apps/xxx -o ./  -O 3=95

### CODE REVIEW

**Comment by kegechen** [comment]
fix:
- https://github.com/linuxdeepin/developer-center/issues/7150
- https://github.com/linuxdeepin/developer-center/issues/7148

**Review by BLumia — APPROVED** [review]

**Pull request merged**
