### PR TITLE
chore: bloom/bloom-dark dci icon tweak

### PR DESCRIPTION
**Pull request by kegechen**
- add bloom-dark icons
- update bloom icons
- add misc/svg2dci.sh
- update to 1.0.14

Issue: https://github.com/linuxdeepin/developer-center/issues/8445, https://github.com/linuxdeepin/developer-center/issues/8242

### CODE REVIEW

**Comment by kegechen** [comment]
@BLumia 测试通过

**Review by BLumia — APPROVED** [review]

**Pull request merged**
